name: build-test

on:
  pull_request:
    branches:
      - zep-vector-memory
  push:
     branches: [ "zep-vector-memory" ]
jobs:
  build:
    runs-on: ubuntu-4c-16GB-150GB
    container: debian:bullseye-slim
    environment: build-test
    services:
      postgres:
        image: ghcr.io/getzep/postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: install certs and build-essential (required by CGO)
        run: apt-get update && apt-get install -y ca-certificates build-essential
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
  
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
  
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: CGO_ENABLED=1 go test -tags=testutils -race -p 1 -v ./...
        env:
          ZEP_LOG_LEVEL: 'info'
          ZEP_OPENAI_API_KEY: ${{ secrets.ZEP_OPENAI_API_KEY }}
          ZEP_ANTHROPIC_API_KEY: ${{ secrets.ZEP_ANTHROPIC_API_KEY }}
          ZEP_STORE_POSTGRES_DSN: 'postgres://postgres:postgres@postgres:5432/?sslmode=disable'